// Code generated by mockery v1.0.0
package mocks

import cashdeposit "github.com/muhammadaser/cash_deposit/cashdeposit"
import mock "github.com/stretchr/testify/mock"

// Mail is an autogenerated mock type for the Mail type
type Mail struct {
	mock.Mock
}

// SendReceiptNotif provides a mock function with given fields: deposit
func (_m *Mail) SendReceiptNotif(deposit cashdeposit.CashDeposit) error {
	ret := _m.Called(deposit)

	var r0 error
	if rf, ok := ret.Get(0).(func(cashdeposit.CashDeposit) error); ok {
		r0 = rf(deposit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
